### ISSUE TITLE
pageInfo always null

### ISSUE THREAD

**Issue by imjulioc** [g18e/ariadne-relay#11]
I've followed the introduction for ariadne-relay with no changes and everytime I try to query pageInfo in the playground I get this error: Cannot return null for non-nullable field FooConnection.pageInfo.

![1](https://user-images.githubusercontent.com/63888039/125689938-56ab2d4c-7b9c-41f2-bd7e-376c7c25dd97.PNG)

Even I have created  my custom type "Aggregate" which declares a count: Int field, and my custom connection with support for it and it works fine. I only get the null error with pageInfo.

![2](https://user-images.githubusercontent.com/63888039/125690002-f403390a-62e3-4027-b9f2-692e49a1909e.PNG)

**Comment by markedwards** [comment]
It’s difficult to tell without a code example, but my guess is this is a snake_case/camelCase mismatch.  If you are using `ariadne.snake_case_fallback_resolvers` you should specify `factory= SnakeCaseConnection` when setting up the connection.  Example:
```
@query.connection("corporates", factory=SnakeCaseConnection)
def resolve_corporates(_, info):
    …

```

**Comment by imjulioc** [comment]
> It’s difficult to tell without a code example, but my guess is this is a snake_case/camelCase mismatch. If you are using `ariadne.snake_case_fallback_resolvers` you should specify `factory=SnakeCaseConnection` when setting up the connection. Example:
> 
> ```
> @query.connection("corporates", factory=SnakeCaseConnection)
> def resolve_corporates(_, info):
>     …
> ```
> 
> For convenience, you can also make SnakeCaseConnection the default:
> 
> ```
> set_default_connection_factory(SnakeCaseConnection)
> ```

Works so fine! I did not notice the impact of using ariadne.snake_case_fallback.
Thanks a lot!.

**Comment by markedwards** [comment]
I should improve the documentation around this because it’s not obvious enough.
